import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useMe, uploadSigned } from "@/lib/auth";
import { PageHeader, STATUS_OPTIONS } from "@/components/brand";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export const Route=createFileRoute("/_authenticated/perfil")({head:()=>({meta:[{title:"Meu perfil — Shopping Hospitalar"},{name:"description",content:"Dados do perfil do colaborador."},{property:"og:title",content:"Meu perfil — Shopping Hospitalar"},{property:"og:description",content:"Dados do perfil do colaborador."}]}),component:Profile});
function Profile(){const {data:me,refetch}=useMe();const p=me?.profile;const [busy,setBusy]=useState(false);if(!p)return null;async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const fd=new FormData(e.currentTarget);let avatar: string | null = p?.avatar_url ?? null;const file=fd.get("avatar");try{if(file instanceof File&&file.size)avatar=await uploadSigned("avatars",`${p?.id}/${file.name}`,file);const {error}=await supabase.from("profiles").update({full_name:String(fd.get("name")).slice(0,120),phone:String(fd.get("phone")).slice(0,30),extension:String(fd.get("extension")).slice(0,20),unit:String(fd.get("unit")).slice(0,100),description:String(fd.get("description")).slice(0,500),status:String(fd.get("status")) as "online"|"offline"|"ausente"|"ocupado",avatar_url:avatar}).eq("id",p?.id??"");if(error)throw error;await refetch();toast.success("Perfil atualizado.");}catch(e){toast.error(e instanceof Error?e.message:"Erro ao salvar");}finally{setBusy(false)}}return <><PageHeader title="Meu Perfil" subtitle="Mantenha seus dados atualizados."/><form onSubmit={save} className="max-w-2xl space-y-5 rounded-xl border bg-card p-6 shadow-card"><div className="grid gap-4 sm:grid-cols-2"><Field label="Nome completo"><Input name="name" maxLength={120} defaultValue={p.full_name}/></Field><Field label="E-mail"><Input disabled defaultValue={p.email??""}/></Field><Field label="Telefone"><Input name="phone" maxLength={30} defaultValue={p.phone??""}/></Field><Field label="Ramal"><Input name="extension" maxLength={20} defaultValue={p.extension??""}/></Field><Field label="Unidade"><Input name="unit" maxLength={100} defaultValue={p.unit??""}/></Field><Field label="Status"><Select name="status" defaultValue={p.status}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{STATUS_OPTIONS.map(s=><SelectItem key={s.value} value={s.value}>{s.label}</SelectItem>)}</SelectContent></Select></Field></div><Field label="Sobre mim"><Textarea name="description" maxLength={500} defaultValue={p.description??""}/></Field><Field label="Foto"><Input name="avatar" type="file" accept="image/jpeg,image/png,image/webp"/></Field><Button disabled={busy}>Salvar alterações</Button></form></>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}