import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarPlus, MapPin, Video } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useMe } from "@/lib/auth";
import { PageHeader,Empty } from "@/components/brand";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle,DialogTrigger } from "@/components/ui/dialog";

export const Route=createFileRoute("/_authenticated/reunioes")({head:()=>({meta:[{title:"Reuniões — Shopping Hospitalar"},{name:"description",content:"Agenda de reuniões."},{property:"og:title",content:"Reuniões — Shopping Hospitalar"},{property:"og:description",content:"Agenda de reuniões."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Page});
function Page(){const{data:me}=useMe();const{data=[]}=useQuery({queryKey:["meetings"],queryFn:async()=>{const{data,error}=await supabase.from("meetings").select("*").order("starts_at");if(error)throw error;return data??[]}});return <><PageHeader title="Reuniões" subtitle="Agenda da equipe." action={me?.canManage?<MeetingDialog/>:undefined}/>{data.length?<div className="grid gap-3 md:grid-cols-2">{data.map(x=><article key={x.id} className="rounded-xl border bg-card p-5 shadow-card"><time className="text-xs font-semibold text-highlight">{new Date(x.starts_at).toLocaleString("pt-BR")}</time><h2 className="mt-2 font-bold">{x.title}</h2>{x.description&&<p className="mt-1 text-sm text-muted-foreground">{x.description}</p>}<div className="mt-3 flex flex-wrap gap-3 text-xs text-muted-foreground">{x.location&&<span className="flex items-center gap-1"><MapPin className="h-3.5 w-3.5"/>{x.location}</span>}{x.link&&<a className="flex items-center gap-1 text-primary underline" href={x.link} target="_blank" rel="noreferrer"><Video className="h-3.5 w-3.5"/>Entrar na reunião</a>}</div></article>)}</div>:<Empty text="Nenhuma reunião agendada."/>}</>}
function MeetingDialog(){const {data:me}=useMe();const qc=useQueryClient();const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!me?.profile)return;setBusy(true);const fd=new FormData(e.currentTarget);try{const title=String(fd.get("title")).trim();const startsAt=String(fd.get("starts_at"));if(!title||!startsAt)throw new Error("Informe título, data e horário.");const link=String(fd.get("link")).trim();if(link&&!/^https?:\/\//i.test(link))throw new Error("Informe um link válido, começando por http:// ou https://.");const{error}=await supabase.from("meetings").insert({title:title.slice(0,160),description:String(fd.get("description")).trim().slice(0,1500)||null,starts_at:new Date(startsAt).toISOString(),location:String(fd.get("location")).trim().slice(0,180)||null,link:link||null,organizer_id:me.profile.id});if(error)throw error;await qc.invalidateQueries({queryKey:["meetings"]});toast.success("Reunião agendada.");setOpen(false);}catch(error){toast.error(error instanceof Error?error.message:"Erro ao agendar reunião.");}finally{setBusy(false)}}return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><CalendarPlus className="h-4 w-4"/>Agendar reunião</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Nova reunião</DialogTitle><DialogDescription>Defina os detalhes que ficarão visíveis para a equipe.</DialogDescription></DialogHeader><form onSubmit={save} className="space-y-4"><Field label="Título"><Input name="title" required maxLength={160}/></Field><Field label="Data e horário"><Input name="starts_at" type="datetime-local" required/></Field><Field label="Local"><Input name="location" maxLength={180} placeholder="Sala de reunião ou Online"/></Field><Field label="Link"><Input name="link" type="url" placeholder="https://"/></Field><Field label="Descrição"><Textarea name="description" maxLength={1500}/></Field><Button className="w-full" disabled={busy}>{busy?"Salvando...":"Agendar"}</Button></form></DialogContent></Dialog>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}